typography_spectrum: 0.3366701412014663
color:
  brandStrength: 0.1676553045399487
  lightness: 0.7917515125591308
  saturation: 0.26341124298051
  rhythmicContrast: 0.26964982924982905
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.0325642516836524
name: Mile High Modular
navigation:
  - name: Road to the Sky
    url: 'http://www.kuxaan-sum.com'
    type: external
title: Modular Synthesizer Revival
description: Patch It
